language: node

node:
  - 5.1

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

install:
  - npm install -g gulp
  - npm install

script:
  - gulp test
